pub mod database;
pub mod repositories;
pub mod search;
pub mod file_storage;
pub mod audit;
pub mod backup;
pub mod usuario_service_impl;
pub mod expediente_service_impl;
pub mod documento_service_impl;
pub mod mappers;
pub mod transaction;

pub use database::Database;
pub use repositories::{ExpedienteRepository, DocumentoRepository, UsuarioRepository};
pub use search::{SearchService, SearchCriteria, SearchResult, ExpedienteSearchResult, DocumentoSearchResult};
pub use file_storage::{FileStorageService, ArchivoGuardado};
pub use audit::{AuditService, AccionAuditoria, RegistroAuditoria, AuditoriaEstadisticas};
pub use usuario_service_impl::UsuarioServiceImpl;
pub use expediente_service_impl::ExpedienteServiceImpl;
pub use documento_service_impl::DocumentoServiceImpl;
pub use transaction::{DatabaseTransaction, execute_in_transaction};
